version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.end
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 4321:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    volumes:
      - data:/var/lib/postgresql/data
  
volumes:
  data: